import type {
  Comment,
  Project,
  Task,
  User,
  Workspace,
} from "./types";

export const seedUser: User = {
  id: "u_ari",
  name: "Ari Utomo",
  email: "ari@trexo.app",
  avatarColor: "#1e88e5",
  authProvider: "email",
};

export const seedWorkspaces: Workspace[] = [
  {
    id: "ws_personal",
    name: "Pribadi",
    type: "personal",
    ownerId: "u_ari",
    color: "#0ea5e9",
    createdAt: "2025-01-04T08:00:00.000Z",
  },
  {
    id: "ws_company",
    name: "PT Sinar Teknologi",
    type: "company",
    ownerId: "u_ari",
    color: "#2196f3",
    createdAt: "2025-01-04T08:05:00.000Z",
  },
];

export const seedProjects: Project[] = [
  // Pribadi
  {
    id: "prj_portfolio",
    workspaceId: "ws_personal",
    name: "Website Portfolio",
    description: "Pembangunan ulang website portfolio pribadi dengan Next.js.",
    icon: "🌐",
    color: "#0ea5e9",
    createdAt: "2025-01-05T09:00:00.000Z",
  },
  {
    id: "prj_learning",
    workspaceId: "ws_personal",
    name: "Belajar Rust",
    description: "Eksplorasi Rust untuk sistem low-level dan CLI tools.",
    icon: "🦀",
    color: "#f97316",
    createdAt: "2025-02-10T09:00:00.000Z",
  },
  // Perusahaan
  {
    id: "prx_dashboard",
    workspaceId: "ws_company",
    name: "Dashboard Analitik",
    description: "Dashboard analitik untuk tim produk — visualisasi metrik real-time.",
    icon: "📊",
    color: "#2196f3",
    createdAt: "2025-01-12T09:00:00.000Z",
  },
  {
    id: "prx_mobile",
    workspaceId: "ws_company",
    name: "Aplikasi Mobile v2",
    description: "Pengembangan ulang aplikasi mobile dengan React Native.",
    icon: "📱",
    color: "#10b981",
    createdAt: "2025-03-01T09:00:00.000Z",
  },
];

const now = "2026-07-31T07:30:00.000Z";

export const seedTasks: Task[] = [
  // ---- Website Portfolio ----
  {
    id: "t_1",
    projectId: "prj_portfolio",
    name: "Desain ulang landing page",
    description:
      "Buat hero section baru dengan animasi halus dan optimasi mobile-first.",
    status: "done",
    source: "own_idea",
    difficulty: "medium",
    priority: "medium",
    steps: [
      { id: "s1", name: "Mood board & referensi", completed: true },
      { id: "s2", name: "Wireframe hi-fi", completed: true },
      { id: "s3", name: "Implementasi komponen", completed: true },
      { id: "s4", name: "Review responsive", completed: true },
    ],
    assigneeId: "u_ari",
    createdAt: "2026-07-10T08:00:00.000Z",
    updatedAt: "2026-07-28T10:00:00.000Z",
  },
  {
    id: "t_2",
    projectId: "prj_portfolio",
    name: "Integrasi CMS headless",
    description: "Sambungkan ke Sanity agar konten blog bisa dikelola tanpa kode.",
    status: "in_progress",
    source: "own_idea",
    difficulty: "hard",
    priority: "medium",
    steps: [
      { id: "s5", name: "Setup proyek Sanity", completed: true },
      { id: "s6", name: "Definisikan schema konten", completed: true },
      { id: "s7", name: "Query GROQ di Next.js", completed: false },
      { id: "s8", name: "Halaman daftar & detail blog", completed: false },
      { id: "s9", name: "Preview mode", completed: false },
    ],
    assigneeId: "u_ari",
    dueDate: "2026-08-05T23:59:00.000Z",
    createdAt: "2026-07-18T08:00:00.000Z",
    updatedAt: "2026-07-30T15:00:00.000Z",
  },
  {
    id: "t_3",
    projectId: "prj_portfolio",
    name: "Setup analytics & SEO",
    description: "Tambahkan Plausible dan meta tag Open Graph.",
    status: "todo",
    source: "user_request",
    difficulty: "easy",
    priority: "medium",
    steps: [],
    assigneeId: "u_ari",
    createdAt: "2026-07-29T08:00:00.000Z",
    updatedAt: "2026-07-29T08:00:00.000Z",
  },
  // ---- Belajar Rust ----
  {
    id: "t_4",
    projectId: "prj_learning",
    name: "Bangun CLI tool untuk konversi gambar",
    description: "Proyek akhir modul: CLI yang mempercepat resize batch.",
    status: "review",
    source: "own_idea",
    difficulty: "hard",
    priority: "medium",
    steps: [
      { id: "s10", name: "Pelajari ownership & borrowing", completed: true },
      { id: "s11", name: "Integrasi crate image", completed: true },
      { id: "s12", name: "Argumen CLI dengan clap", completed: true },
      { id: "s13", name: "Benchmark vs ImageMagick", completed: false },
    ],
    assigneeId: "u_ari",
    createdAt: "2026-06-20T08:00:00.000Z",
    updatedAt: "2026-07-30T09:00:00.000Z",
  },
  {
    id: "t_5",
    projectId: "prj_learning",
    name: "Baca 'The Rust Book' bab 10-15",
    description: "Lanjutkan materi generics, traits, dan lifetimes.",
    status: "todo",
    source: "own_idea",
    difficulty: "medium",
    priority: "medium",
    steps: [],
    assigneeId: "u_ari",
    createdAt: "2026-07-28T08:00:00.000Z",
    updatedAt: "2026-07-28T08:00:00.000Z",
  },
  // ---- Dashboard Analitik ----
  {
    id: "t_6",
    projectId: "prx_dashboard",
    name: "Endpoint API real-time metrik",
    description: "Buat WebSocket untuk push metrik setiap 5 detik.",
    status: "in_progress",
    source: "user_request",
    difficulty: "hard",
    priority: "medium",
    steps: [
      { id: "s14", name: "Desain payload pesan", completed: true },
      { id: "s15", name: "Implementasi server WS", completed: false },
      { id: "s16", name: "Reconnect & backoff client", completed: false },
    ],
    assigneeId: "u_ari",
    dueDate: "2026-07-30T23:59:00.000Z",
    createdAt: "2026-07-15T08:00:00.000Z",
    updatedAt: "2026-07-30T11:00:00.000Z",
  },
  {
    id: "t_7",
    projectId: "prx_dashboard",
    name: "Komponen grafik garis performa",
    description: "Chart performa harian dengan zoom & tooltip.",
    status: "review",
    source: "user_request",
    difficulty: "medium",
    priority: "medium",
    steps: [
      { id: "s17", name: "Pilih library charting", completed: true },
      { id: "s18", name: "Bind data ke props", completed: true },
      { id: "s19", name: "Implementasi tooltip", completed: true },
      { id: "s20", name: "Mode gelap", completed: false },
      { id: "s21", name: "Aksesibilitas (a11y)", completed: false },
    ],
    assigneeId: "u_ari",
    createdAt: "2026-07-12T08:00:00.000Z",
    updatedAt: "2026-07-29T16:00:00.000Z",
  },
  {
    id: "t_8",
    projectId: "prx_dashboard",
    name: "Halaman login SSO karyawan",
    description: "Integrasi SSO Google untuk akun perusahaan.",
    status: "done",
    source: "user_request",
    difficulty: "medium",
    priority: "medium",
    steps: [
      { id: "s22", name: "Daftar OAuth credentials", completed: true },
      { id: "s23", name: "Alur callback", completed: true },
    ],
    assigneeId: "u_ari",
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-20T10:00:00.000Z",
  },
  {
    id: "t_9",
    projectId: "prx_dashboard",
    name: "Perbaiki bug filter tanggal",
    description: "Filter rentang tanggal melewatkan data weekend.",
    status: "todo",
    source: "user_request",
    difficulty: "easy",
    priority: "medium",
    steps: [],
    assigneeId: "u_ari",
    dueDate: "2026-08-02T23:59:00.000Z",
    createdAt: "2026-07-30T08:00:00.000Z",
    updatedAt: "2026-07-30T08:00:00.000Z",
  },
  // ---- Aplikasi Mobile v2 ----
  {
    id: "t_10",
    projectId: "prx_mobile",
    name: "Migrasi navigasi ke Expo Router",
    description: "Pindah dari React Navigation ke Expo Router v3.",
    status: "in_progress",
    source: "own_idea",
    difficulty: "medium",
    priority: "medium",
    steps: [
      { id: "s24", name: "Audit layar eksisting", completed: true },
      { id: "s25", name: "Setup Expo Router", completed: true },
      { id: "s26", name: "Migrasi tab navigator", completed: false },
      { id: "s27", name: "Migrasi deep link", completed: false },
    ],
    assigneeId: "u_ari",
    createdAt: "2026-07-22T08:00:00.000Z",
    updatedAt: "2026-07-31T07:00:00.000Z",
  },
  {
    id: "t_11",
    projectId: "prx_mobile",
    name: "Onboarding interaktif",
    description: "3 layar onboarding dengan animasi Lottie.",
    status: "todo",
    source: "user_request",
    difficulty: "easy",
    priority: "medium",
    steps: [],
    assigneeId: "u_ari",
    createdAt: "2026-07-25T08:00:00.000Z",
    updatedAt: "2026-07-25T08:00:00.000Z",
  },
];

export const seedComments: Comment[] = [
  {
    id: "c_1",
    taskId: "t_2",
    userId: "u_ari",
    content: "Schema kontennya sudah fix, lanjut query GROQ.",
    createdAt: "2026-07-29T10:00:00.000Z",
  },
  {
    id: "c_2",
    taskId: "t_2",
    userId: "u_ari",
    content: "Hati-hati pagination untuk daftar blog, pakai limit + offset.",
    createdAt: "2026-07-30T14:30:00.000Z",
  },
  {
    id: "c_3",
    taskId: "t_6",
    userId: "u_ari",
    content: "Coba library ws untuk node server, lebih ringan dari socket.io.",
    createdAt: "2026-07-30T11:10:00.000Z",
  },
  {
    id: "c_4",
    taskId: "t_7",
    userId: "u_ari",
    content: "Tooltip sudah responsif, tinggal mode gelap.",
    createdAt: "2026-07-29T16:05:00.000Z",
  },
];

export const seedNow = now;
